export type Mens = {
  naam: string;
  slug: string;
  org: string;
  foto: string | null;
  bio: string[];
};


export const mensen: Mens[] = [
  { naam: "Maroesja van der Pols", slug: "maroesja-van-der-pols", org: "A Motion Company", foto: "/team/maroesja-van-der-pols.jpg", bio: [`<h4><b>Oprichter en directeur 7Life Netwerk</b></h4>
Als oprichter van het 7Life Netwerk ben ik ongelooflijk blij met de mooie ontwikkelingen ten aanzien van dienstverlening, samenwerking en toepassing. Sterke communicatie, op allerlei gebieden, heeft mijn hart en interesse. En dat blijft de kern van 7Life: wij bieden inzicht in communicatie en interactie. Hoe kijk je naar de wereld om je heen, hoe luister je naar anderen, hoe leer en motiveer jij. Hoe werk je samen, wanneer heb je een klik en wat gebeurt er als je niet gehoord, niet gewaardeerd wordt? Hele handige inzichten die je nodig hebt, op allerlei momenten en in heel veel situaties. En dat is ons "pakkie aan": communicatie die werkt, voor jou en met jou.`, `Daarbij kan ik mijn persoonlijke expertise op het gebied van (strategisch) HRM, duurzame talentontwikkeling en bedrijfskunde goed kwijt binnen het 7Life Model en ons netwerk. Juist voor deze expertise gebieden kunnen we mooie tools ontwikkelen en advies geven dat mensen zowel als organisaties verrijkt.`, `Als ondernemer ben ik bovendien een nieuw gebied in gestapt van schrijven, of dat nu boeken of tijdschriften en lesmaterialen zijn. Geweldig om opnieuw uitgedaagd te worden en verder te ontwikkelen.`, `En dat past dan weer prima bij 7Life: we blijven continu investeren in mooie ontwikkelingen, die bijdragen aan oplossingen die werken. Samen met mensen die iets te bieden hebben en ons - en hopelijk ook anderen - inspireren.`] },
  { naam: "Monique Aalberts", slug: "monique-aalberts", org: "Kindercoach Josia", foto: "/team/monique-aalberts.jpg", bio: [`<h4><b>Kluis7 Methodiek, kinderen, scholen, gezinnen</b></h4>`] },
  { naam: "Jo Krill", slug: "jo-krill", org: "7LIFE Nederland", foto: "/team/jo-krill.jpg", bio: [`<h4><strong>Business strategist, partner en organisatieontwikkeling.</strong></h4>`] },
  { naam: "Wilbert de Kroon", slug: "wilbert-de-kroon", org: "Diemen & Van Gestel", foto: "/team/wilbert-de-kroon.jpg", bio: [`<h4><strong>Stand up consultant, executive coach en trainer</strong></h4>`] },
  { naam: "Janine Pormes", slug: "janine-pormes", org: "Pormes Training", foto: "/team/janine-pormes.jpg", bio: [`Ik ben Janine Pormes, eigenaar van Pormes Training.`, `Als communicatietrainer en coach werk ik al meer dan 20 jaar met teams en individuele professionals. Mijn doel is altijd hetzelfde: grip krijgen op communicatie zodat deze effectiever wordt ingezet en verbinding en samenwerking versterkt.`, `Daarbij maak ik graag gebruik van 7Life. Een prachtig instrument wat inzicht biedt in ieders eigen communicatie en in de communicatie van de ander. Met 7Life ontdek je niet alleen wat je eigen start en verwachting is binnen communicatie, maar ook wat die ander nodig heeft en hoe je de kloof die er soms is kan overbruggen. Je mag thuis komen bij jezelf en bij de ander zodat de potentie die een ieder heeft tot volle bloei komt!`] },
  { naam: "Gideon Beeftink", slug: "gideon-beeftink", org: "Huiswerkbegeleiding Haarlem", foto: "/team/gideon-beeftink.png", bio: [`<h4><strong>Onderwijs, coaching en begeleiding van leerlingen, ouders en stellen.</strong></h4>
Hoe prachtig is het om een kind te zien dat weet wat hij wil. Dat weet waarin hij goed is, waar zijn talenten liggen en waardoor hij gemotiveerd wordt. De Excelleerscan werpt een blik in de unieke leer- en communicatiestijl van uw kind en verheldert waarom hij de dingen doet zoals hij ze doet. Met deze handleiding kunnen wij —ouders en begeleiders — hem helpen het maximale potentieel uit zichzelf te halen en beter te gaan leren.`, `Haal het beste uit uw kind en uzelf:`, `Neem contact op voor een Excelleerscan speciaal voor tieners of een 7 Life scan voor volwassenen!`, `"De tuinier laat de plant niet groeien. Het is de taak van de tuinier om de optimale voorwaarden te creëren voor groei".`] },
  { naam: "Marcel Pormes", slug: "marcel-pormes", org: "Trainer", foto: "/team/marcel-pormes.jpg", bio: [`<h4><b>Opvoeding, Jongeren</b></h4>`] },
  { naam: "Sandy van Zuthem", slug: "sandy-van-zuthem", org: "Trainer", foto: null, bio: [] },
  { naam: "Michèl van Zuthem", slug: "michel-van-zuthem", org: "Trainer", foto: "/team/michel-van-zuthem.jpg", bio: [] },
  { naam: "Jan Willem Janse", slug: "jan-willem-janse", org: "Werkelijke verbinding (Jan Willem Janse)", foto: "/team/jan-willem-janse.jpg", bio: [`<h4><strong>Werken aan werkelijke verbinding op basis van je 7Life-scan</strong></h4>
Heb jij een 7Life-scan gemaakt of wil je er een aanvragen? En heb je behoefte aan een goed gesprek erover? Kun je direct enkele adviezen gebruiken? Meld je dan nu aan via mijn website.`] },
  { naam: "Marije van den Berg", slug: "marije-van-den-berg", org: "Be Excellent academy", foto: "https://accent-dev.nl/7life/wp-content/uploads/2023/12/Marije-van-den-Berg-1.jpg", bio: [`Ik ben Marije van den Berg, een bevlogen coach en trainer op het gebied van persoonlijke ontwikkeling en leiderschap. Mijn werk is fantastisch, ik mag steeds weer het goud in mensen naar boven brengen. Inmiddels werk ik al jaren met 7LIFE en heb ik al honderden assessments teruggekoppeld, vele coachtrajecten afgerond en teamtrainingen gegeven. Waarom mijn ogen gaan stralen als ik deel over de inzet van 7LIFE is omdat het assessment een ontwikkelmodel is dat de potentie in elk mens naar boven brengt. Of je nu al weet wie je bent en wat jij uniek te brengen hebt in onze maatschappij, of niet. Wij ontwarren dat voor jou, zodat jij jezelf mag verwonderen over de mooie persoon die jij bent.`, `Benieuwd naar meer? <a href="https://calendly.com/bureaudelight/telefonisch-belconsult-met-marije-van-den-berg" target="_blank" rel="noopener">Plan een gratis telefonische coachsessie in via deze link</a>.`] },
  { naam: "Arend Voogt", slug: "arend-voogt", org: "New Season Coaching", foto: "/team/arend-voogt.png", bio: [`Ik ben Arend Voogt (41), projectleider en coach leiderschap en talentontwikkeling bij de Politie.`, `Al meer dan tien jaar begeleid ik professionals en leidinggevenden in de publieke sector bij hun persoonlijke en professionele groei. Mijn kracht ligt in het zichtbaar maken van wat er écht speelt, in de bovenstroom én de onderstroom, en in het creëren van ontwikkeling die blijft hangen.`, `Wat mij enthousiast maakt over 7LIFE, is dat deze methode mensen op een toegankelijke en krachtige manier helpt om zichzelf beter te begrijpen. De Leadershipscan geeft taal aan gedrag, drijfveren en talenten, en vormt een solide basis voor groei in leiderschap, samenwerking en communicatie. Het is precies die combinatie van zelfinzicht en praktische toepasbaarheid waar ik in geloof.`, `Binnen mijn trainingen en coachtrajecten richt ik me op het versterken van persoonlijk leiderschap, teamdynamiek en moreel bewustzijn. Ik werk met bewezen modellen zoals de Ladder van Samenwerking en het moreel kompas. Methodieken die naadloos aansluiten bij het gedachtengoed van 7LIFE. Mijn stijl is nuchter, energiek en reflectief. Uiteraard met voldoende ruimte voor humor.`, `Ik geloof dat leiderschap begint bij zelfinzicht en groeit in verbinding met anderen. Vanuit dat vertrekpunt begeleid ik mensen om hun waarden, overtuigingen en gedrag te ontdekken. Ik wil dat zij met vertrouwen, duidelijkheid en impact hun rol kunnen innemen op het werk én daarbuiten.`] },
  { naam: "Stanley Neyndorff", slug: "stanley-neyndorff", org: "GIC Consultancy", foto: "/team/stanley-neyndorff.jpg", bio: [`Zorg niet alleen voor toegevoegde waarde met wat je doet, maar wees ook onderscheidend door wie je bent.
Mensen in beweging krijgen en houden door hen te helpen bij het definiëren en realiseren van doelen (persoonlijk/zakelijk), dat is mijn passie. Op basis van de juiste verstandhouding (warmte en vertrouwen) voer ik op holistische wijze het proces van analyseren, definiëren, identificeren, herkennen, erkennen, raadgeven en begeleiden.`, `Als raadgever ben ik voor zzp\` ers, MKB-ondernemers en managers een gesprek- en sparringspartner. Met gezond verstand ondersteun ik in het bedenken van creatieve oplossingen en geef inspiratie, train, counsel en adviseer ondernemers, directies en management op het gebied van uiteenlopende persoonlijke-, ondernemers- en managementvraagstukken. Met als doel: levensveranderend ondernemen!`] },
  { naam: "Bertil Moraal", slug: "bertil-moraal", org: "Docent, Studentbegeleider en Voorzitter Curriculum Team", foto: "/team/bertil-moraal.jpg", bio: [`<blockquote><em>"Studenten zijn jonge mensen én aanstaande professionals. Zodra zij starten met een studie gaan ze een reis aan vol ontdekkingen. Niet alleen dat vak dat ze gekozen hebben staat daarbij centraal, maar ook de vraag wie jij bent in al die verschillende werk-, studie- en leefsituaties. Dat is een complexe, maar ook boeiende reis. 7Life geeft hen een houvast om naar zichzelf te kunnen kijken én zichzelf meer te begrijpen. Maar 7Life geeft ook taal. Studenten ontdekken hiermee dat mensen soms écht anders in elkaar zitten en dat je kunt kiezen hoe jij de brug naar die ander slaat. Die ontdekking en daarmee gaan werken is een hele waardevolle toevoeging aan een onderwijscurriculum. Zo komen mens, vak en werkprakrijk op een geweldige en leerzame manier samen!"</em></blockquote>
<strong>Bertil Moraal</strong>
Docent, Studentbegeleider en Voorzitter Curriculum Team
Opleiding HRM`] },
  { naam: "Alex ten Cate", slug: "alex-ten-cate", org: "Life2Lead", foto: "/team/alex-ten-cate.png", bio: [`<h4><b>Leiderschap, teamdynamiek en verandering</b></h4>
Persoonlijk leiderschap, teamdynamiek in context en leidinggeven aan verandering.`] },
  { naam: "Marion van der Kraan", slug: "marion-van-der-kraan", org: "ROOTSZ - the impact network", foto: "/team/marion-van-der-kraan.jpg", bio: [`<h4><b>Kwartiermaker, Veranderaar, Organisatie- &amp; managementadvies</b></h4>`] },
  { naam: "Barbara Mentink", slug: "barbara-mentink", org: "De Schrijvernij", foto: null, bio: [`<h4><b>Dyslexie en andere conceptueel denkers, ontwerper Spelling Zonder Regels, leercoach, mediator</b></h4>`] },
  { naam: "Prashant Sahtoe", slug: "prashant-sahtoe", org: "Sahtoe", foto: null, bio: [`<h4><b>Finance en Consulting</b></h4>`] },
  { naam: "Hugo Bot", slug: "hugo-bot", org: "BOTH Coaching", foto: "https://accent-dev.nl/7life/wp-content/uploads/2023/12/Hugo-Bot.jpg", bio: [] },
  { naam: "Marc Wilhelmus", slug: "marc-wilhelmus", org: "Marc Wilhelmus Coaching en Training", foto: "/team/marc-wilhelmus.jpg", bio: [`<strong>Wat doe ik?</strong>
Ik ben Marc: coach, schrijver, lifeplanner en trainer. Ik verzorg onder andere trainingen voor financieel adviseurs, financieel planners, bedrijven en consumenten. Daarnaast help ik cliënten op het gebied van stressherstel en andere klachten, hun loopbaan en hun relatie met geld.`, `Wat mij kenmerkt: inspirerend, praktisch, concreet en authentiek!`, `<strong>Achtergrond</strong>
Ik heb jarenlang zelf als financieel adviseur en planner gewerkt. Wat ik nooit begreep is dat geldgedrag en de mindset over geld weinig in de financiële plannen werden meegenomen. En wat me nog meer verbaasde, is dat vooral cliënten zich niet bewust zijn van hun relatie met geld.`, `<strong>Passie</strong>
Rondom geld heerst veel emotie, taboe, schaamte maar ook ego. Dit wil ik graag (helpen) doorbreken. Daarom werk ik met zowel cliënten als financieel adviseurs/planners die dat wat ze leren kunnen toepassen in hun eigen contact met cliënten. Zo zorg ik op verschillende niveaus dat cliënten begeleid worden naar een goede en gezonde relatie met geld. Met als doel een effectief te realiseren toekomst met een financieel bewust plan.`, `<strong>7LIFE</strong>
Toen ik zo’n 5 jaar geleden kennismaakte met 7LIFE wist ik het. Hier wil ik iets mee. De combinatie van het 7LIFE assessment en mijn achtergrond in de financiële wereld hebben geleid tot het ontwikkelen van de geldtype scan van 7LIFE met als doel ECHTE gesprekken over geld.`, `Zo kijk je met de geldtype scan naar jouw relatie en gedrag met gelden en hoe je je hierin kunt ontwikkelen. Ook creëert de scan bewustwording over hoe je in stressvolle situaties omgaat met geld. Met die inzichten kun je (samen met je cliënt) een plan maken gericht op de toekomst en kunnen mogelijke problemen voorkomen worden.`, `Sindsdien werk ik samen met 7LIFE als business partner en trainer voor financieel adviseurs en financieel planners. We hebben een praktisch trainingsprogramma ontwikkeld: "Geld gedrag en adviseren met geldtypen". Waarbij jij als financieel planner of adviseur in een dag de 6 praktijkpunten FFP haalt, die jaarlijks nodig zijn. Daarna is er ook een mogelijkheid om je in een halve dag te laten accrediteren zodat je zelf aan de slag kunt gaan als 7LIFE geldtype adviseur/planner.`, `<strong>Boek “Voor hetzelfde geld gelukkig”</strong>
Naast coach, lifeplanner en trainer ben ik ook auteur van het boek: "Voor hetzelfde geld gelukkig!” Met de geldscan als basis neem ik je mee in hoe je een goede vriend kunt worden met je geld en ontdek je wat jij nodig hebt voor een leuker, vervullender leven. Het schrijfproces was lang, maar ook bijzonder en een echt avontuur op zichzelf. Ik heb veel over mezelf én over schrijven geleerd. Of ik het nog een keer zou doen? Wie weet… Misschien ooit een kinderboek, of zelfs iets in het Engels.`, `Meer weten over het trainingsprogramma, mijn boek, de geldscan en/of mij als coach? Neem gerust contact met me op <a href="mailto:info@marcwilhelmus.nl" target="_blank" rel="noopener">info@marcwilhelmus.nl</a>.`] },
  { naam: "Sarah Geschiere", slug: "sarah-geschiere", org: "Trainer", foto: null, bio: [] },
  { naam: "Mia Wilsterman", slug: "mia-wilsterman", org: "Trainer", foto: null, bio: [] },
  { naam: "Melissa Brinkhof-Kanis", slug: "melissa-kanis", org: "Trainer", foto: "/team/melissa-kanis.jpeg", bio: [`Als adviseur organisatie-inrichting begeleid ik dagelijks ondernemers om de volgende stap in hun bedrijf te zetten (bedrijfsopvolging begeleiden, inrichten van processen, effectieve communicatie, vacatures). Tijdens een organisatieverandering spelen er vaak veel zaken rondom communicatie, maar ook spanning, ‘druk’, sfeer spelen hierin mee.`, `Met 7Life krijgt de ondernemer alvast een eerste inzicht in zijn/haar communicatiestijlen. Waarna ik de vertaalslag maak naar het bedrijf van de ondernemer en zijn dagelijkse praktijk. Zo gaan we samen gericht aan de slag om zowel de menskant als de proceskant te optimaliseren. Mijn kracht is om snel te doorzien waar knelpunten liggen binnen een organisatie, zodat we écht bij de kern blijven wat er speelt. Zodat een verandering een duurzame verandering wordt binnen familiebedrijven.`] },
  { naam: "Merel Ducaat", slug: "merel-ducaat", org: "Trainer", foto: null, bio: [] },
  { naam: "Christien Veeneman", slug: "christien-veeneman", org: "Trainer", foto: null, bio: [] },
  { naam: "Karine van den Noort", slug: "karine-van-den-noort", org: "Trainer", foto: null, bio: [] },
  { naam: "Ben de Backker", slug: "ben-de-backker", org: "Trainer", foto: null, bio: [] },
  { naam: "Larissa van der Haar", slug: "larissa-van-der-haar", org: "Trainer", foto: null, bio: [] },
  { naam: "Lyda Struijk", slug: "lyda-struijk", org: "Trainer", foto: "/team/lyda-struijk.jpg", bio: [`Ik ben Lyda Struijk en sinds een paar jaar coach en trainer bij Bureau Delight van Marije van den Berg.`, `Mijn ogen gaan stralen als ik zie dat er bij andere mensen lampjes gaan branden. Als je bij ons een coachtraject aangaat starten we altijd met het afnemen van een 7LIFE assessment. Het is zo gaaf om te zien dat het bespreken van het assessment zoveel inzicht geeft. Het laat zien waarom je op een bepaalde manier keuzes maakt, wat je nodig hebt, hoe je om kunt gaan met stress en waar je dan behoefte aan hebt. Inzicht in jouw 7LIFE profiel geeft woorden aan de onuitgesproken dingen en mogelijke worstelingen.`, `We gaan samen met jou ontdekken wat voor moois er in jou zit en hoe je dat ten volle kan gaan inzetten in je leven. Daarmee kun je gaan groeien en bloeien op de plaats die voor jou bestemd is.`, `Ben je benieuwd naar meer plan dan een gratis coach sessie in via deze link: <a href="https://calendly.com/lyda-bureaudelight/30min" target="_blank" rel="noopener">https://calendly.com/lyda-bureaudelight/30min</a>`] },
  { naam: "Niels Leijtens", slug: "niels-leijtens", org: "Trainer", foto: null, bio: [] },
  { naam: "Simone ten Cate", slug: "simone-ten-cate", org: "Trainer", foto: null, bio: [] },
  { naam: "Hasti van Vliet", slug: "hasti-van-vliet", org: "Trainer", foto: "/team/hasti-van-vliet.jpeg", bio: [`<strong>Hasti van Vliet</strong> is founder van <em>Incredible Studios</em> en ondernemerscoach voor <strong>MKB-ondernemers (2–60 fte)</strong> met een grootse visie en de ambitie om hun bedrijf en leiderschap naar het volgende niveau te brengen.`, `Ze helpt ondernemers hierbij door <em>Scaling</em><em> </em><em>Up</em>, leiderschapsontwikkeling en systemisch inzicht te combineren — een krachtige mix die precies blootlegt wat nodig is om versnelling te creëren.`, `Met haar scherpe blik en jarenlange ervaring begeleidt Hasti ondernemers in het bepalen waar ze naartoe willen groeien, wat hun bedrijf daarvoor nodig heeft en wie zij als leider moeten zijn om dat waar te maken.`, `Haar missie is helder: ondernemers helpen door te breken naar hun next level, met een bedrijf dat zowel resultaat als voldoening oplevert.`, `Wat Hasti aanspreekt in <em>7LIFE</em> is hoe het inzicht geeft in waar jouw <strong>Incredible</strong> ligt en welk onbenut potentieel nog op jou wacht. Het sluit naadloos aan bij haar visie: dat groei naar de next level vraagt dat je boven jezelf uitstijgt en al het goud in jezelf inzet — voor jezelf, je leiderschap én je bedrijf.`] },
  { naam: "Sylvia Schouten", slug: "sylvia-schouten", org: "7Life trainer", foto: "/team/sylvia-schouten.jpeg", bio: [`Mijn naam is Sylvia Schouten. Ik ben HR dienstverlener voor het MKB. Ondersteunend voor kleinere bedrijven en interim voor bedrijven op tijdelijke basis bij vervanging of ziekte.`, `<strong>Daarnaast ben ik 7Life trainer!</strong>`, `“Ieder z’n vak”, zeggen we altijd. Maar communicatie? Dat is voor iedereen. Zakelijk en privé. Hoe vaak merk je dat je gesprekspartner op een heel ander level lijkt te zitten? Wanneer je voelt dat de ander jou niet begrijpt, of jij de ander niet begrijpt, dan is er sprake van miscommunicatie.`, `In taal zit kracht, overtuiging, passie en kennis. Met de 7Life scan en LeiderschapScan laten we mensen begrijpen welke taal zij spreken. Want iedereen heeft meerdere communicatiestijlen maar er is altijd een voorkeurstijl die dominant is.`, `Je gaat zien hoe andere stijlen zich manifesteren, daarin zit de win-win. Communicatie is immers begrip hebben voor de ander en tot mooie conclusies komen of gewoon mooie gesprekken hebben die niet tot discussie leiden maar tot mooie inzichten.`] },
  { naam: "Erica Duenk", slug: "erica-duenk", org: "Trainer", foto: "/team/erica-duenk.jpeg", bio: [`<h3><strong>Erica Duenk – To Be is Key</strong></h3>
Ik ben een bevlogen trainer en spreker die mensen helpt om zichzelf beter te leren kennen. Mijn kracht ligt in het terugbrengen van complexiteit naar eenvoud, zodat helder wordt wat er werkelijk toe doet en mensen in beweging komen.`, `Ik help mensen hun identiteit en hun uniek zijn te ontdekken, zodat zij inzicht krijgen in zichzelf, overzicht in hun situatie en uitzicht op verandering en groei. Ik sta erom bekend dat ik het goud in de ander zie en dit help benoemen en versterken.`, `Ik ben enthousiast over 7LIFE omdat het een heldere en toegankelijke tool is om jezelf beter te leren kennen én om de brug te slaan naar anderen in communicatie. Het vergroot begrip, versterkt samenwerking en brengt bovenal meer verbinding binnen teams, organisaties en relaties.`] },
];
